name: World-Manager
version: 2.2.5
author: hyperspace_pilot
main: de.hyper.worlds.domain.WorldManagement
api-version: 1.18
softdepend:
  - FastAsyncWorldEdit
  - CoreProtect
commands:
  world:
    aliases:
      - worlds
      - welt
      - welten
  worldconsole:
    aliases:
      - consoleworld