package de.hyper.worlds.common.enums;

public enum SettingType {

    BLOCK_PHYSICS,
    TIME,
    WEATHER,
    REDSTONE,
    RANDOMTICKSPEED,
    LEAF_DECAY,
    UNLOADING,
    SIZE,
    EXPLOSION,
    POTION,
    HUNGER,
    MOB_DROPS,
    MOB_SPAWNING,
    BLOCK_SPREAD,
    ENTITY_BLOCK_FORM,
    BLOCK_FORM,
    BLOCK_FROM_TO,
    BLOCK_GROW,
    BLOCK_FERTILIZE,
    BLOCK_BURN,
    GAMEMODE,
    WORLDCHAT,
    WORLDINVENTORIES;
}
